apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busolag-dev
spec:
  project: default
  source:
    repoURL: https://gitlab.com/BusolaG/infra-automation.git
    chart: busolaG
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: busolag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    valueFiles:
      - /home/ubuntu/infra-automation/busolaG/charts/values-dev.yaml