apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/busolagbadero/infra-automation.git
    chart: busolaG
    targetRevision: 'HEAD'
    helm:
     valueFiles:
     - infra-automation/busolaG/charts/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: busolag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


